### ISSUE TITLE
Settings unavailable when module update is available

### ISSUE THREAD

**Issue by lab51-bob** [trustpilot/plugin-magento2#31]
We are unable to edit settings in Magento backend because there is a module update. Unwanted behavior IMHO because a build can't be easily done on production, but settings wil have to be available.

**Comment by Boldonglen** [comment]
I am having the same issue. It says that you need to download the latest version "2.6.408" however after clicking the marketplace link that is presented there is no download for that version the latest is "2.6.355" and thats the version I currently have installed. As the OP says not having the latest version should not stop you from updating config and using the extension.

**Comment by VitaVal** [comment]
Hi, @Boldonglen @lab51-bob,

You can install Trustpilot plugin in 2 ways: 
1 - from the Magento Marketplace. Unfortunately it usually takes quite a while for the latest version of plugin to appear on the Magento marketplace due to a long review process. 
2 - within Composer. When using the Composer, you will always get the latest version.

Please follow the Composer installation process:
https://support.trustpilot.com/hc/en-us/articles/360021194414--Trustpilot-s-free-Magento-2-plugin-download-install-and-configure-it#download-install-plugin-via-composer

Let us know if you have any other questions.
Kind Regards,
Trustpilot Team
