### ISSUE TITLE
Category product sorting/paging problem after upgrade to 2.4.0 or 2.4.1

### ISSUE THREAD

**Issue by pfcgroot** [trustpilot/plugin-magento2#82]
After upgrading magento from 2.3.6 to 2.4.0 the product paging and sorting is not working properly anymore with version 2.6.555. Category pages just show **all** products in semi-random order and **sorting** doesn't work anymore as soon as a trustbox is placed anywhere on the category page. This issue is very similar to a previous issue (#66). Removing the trustbox solves the problem.

Exactly the same issue happens when upgrading to 2.4.1.

**Comment by kabalas2** [comment]
Hi, I had the same issue, it is because block trustpilot.head.trustbox is loading in the head. after changing loading in the footer it starts work. 
vendor/trustpilot/module-reviews/Block/Trustbox.php 134:
`$products = $block->getLoadedProductCollection();`

just product collection should be load later. after head.

**Comment by arunas-stonis** [comment]
It was fixed in version 2.6.560
